<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

declare(strict_types=1);

namespace bookingextension_agent\local\wbagent\examples\tasks;

use bookingextension_agent\local\wbagent\base_task;
use bookingextension_agent\local\wbagent\services\preflight_result_v2;
use bookingextension_agent\local\wbagent\services\task_prompt_contract;

/**
 * Spawn child task companion for scenario C.
 *
 * The parent task binds batch_label and ticket_id into this child input via
 * output_bindings. This class shows the child side of that contract.
 *
 * @package    bookingextension_agent
 * @copyright  2026 Wunderbyte GmbH <info@wunderbyte.at>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class spawn_child_example_task extends base_task {
    /** Stable task name. */
    public const TASK_NAME = 'examples.spawn_child_example';

    /**
     * Constructor.
     */
    public function __construct() {
        parent::__construct(true);
    }

    /**
     * @return string
     */
    public function get_name(): string {
        return self::TASK_NAME;
    }

    /**
     * @return array<string,mixed>
     */
    public function get_schema(): array {
        return [
            'version' => 1,
            'description' => 'Example spawned child task for scenario C.',
            'readonly' => true,
            'properties' => [
                'child_label' => [
                    'type' => 'string',
                    'description' => 'Child-specific label generated by parent.',
                    'required' => true,
                ],
                'batch_label' => [
                    'type' => 'string',
                    'description' => 'Parent-provided batch label (via output binding).',
                    'required' => true,
                ],
                'ticket_id' => [
                    'type' => 'string',
                    'description' => 'Parent-provided ticket id (via output binding).',
                    'required' => true,
                ],
            ],
            'required' => ['child_label', 'batch_label', 'ticket_id'],
        ];
    }

    /**
     * @return array<string,mixed>
     */
    public function get_example_input(): array {
        return [
            'child_label' => 'child-1',
            'batch_label' => 'example demo batch',
            'ticket_id' => 'SP-EXAMPLE123',
        ];
    }

    /**
     * @return task_prompt_contract
     */
    public function get_prompt_contract(): task_prompt_contract {
        return new task_prompt_contract([
            'intent' => 'Execute one spawned child step for a parent workflow.',
            'anchors' => ['child_label', 'batch_label', 'ticket_id'],
            'minimal_input' => ['child_label', 'batch_label', 'ticket_id'],
            'example_input' => $this->get_example_input(),
            'namespace' => 'examples',
            'version' => 1,
            'capabilities' => [],
            'context_scopes' => ['module'],
        ]);
    }

    /**
     * @param array<string,mixed> $input
     * @return array{valid:bool,errors:array<int,string>,ambiguities:array<int,string>}
     */
    public function check_structure(array $input): array {
        $errors = [];
        foreach (['child_label', 'batch_label', 'ticket_id'] as $requiredfield) {
            if (trim((string)($input[$requiredfield] ?? '')) === '') {
                $errors[] = 'Field "' . $requiredfield . '" is required.';
            }
        }

        return [
            'valid' => empty($errors),
            'errors' => $errors,
            'ambiguities' => [],
        ];
    }

    /**
     * @param array<string,mixed> $input
     * @param int $contextid
     * @param int $userid
     * @return preflight_result_v2
     */
    public function preflight(array $input, int $contextid, int $userid): preflight_result_v2 {
        $structure = $this->check_structure($input);
        if (!($structure['valid'] ?? false)) {
            $issues = array_map(static fn(string $error): array => [
                'code' => 'EXAMPLE_INPUT_INVALID',
                'severity' => 'hard_block',
                'message' => $error,
            ], $structure['errors']);
            return preflight_result_v2::invalid($issues);
        }

        return preflight_result_v2::ok([
            'child_label' => trim((string)$input['child_label']),
            'batch_label' => trim((string)$input['batch_label']),
            'ticket_id' => trim((string)$input['ticket_id']),
            'contextid' => $contextid,
            'userid' => $userid,
        ]);
    }

    /**
     * @param array<string,mixed> $preparedinput
     * @param int $contextid
     * @param int $userid
     * @return array<string,mixed>
     */
    public function execute(array $preparedinput, int $contextid, int $userid): array {
        $childlabel = trim((string)($preparedinput['child_label'] ?? ''));
        $batchlabel = trim((string)($preparedinput['batch_label'] ?? ''));
        $ticketid = trim((string)($preparedinput['ticket_id'] ?? ''));

        return [
            'status' => 'executed',
            'detail' => '[SCENARIO-C-CHILD] spawn child example executed',
            'usermessage' => '[SCENARIO-C] Child step ' . $childlabel . ' completed for batch ' . $batchlabel . '.',
            'resultid' => abs((int)crc32($childlabel . '|' . $ticketid . '|' . $contextid . '|' . $userid)),
            'child_label' => $childlabel,
            'batch_label' => $batchlabel,
            'ticket_id' => $ticketid,
        ];
    }
}
