"""
Wunderbyte Moodle Trial Key Endpoint
=====================================
Mount this FastAPI router in your existing LiteLLM / FastAPI application.

Requirements
------------
    pip install fastapi httpx litellm

Environment variables expected
--------------------------------
    LITELLM_MASTER_KEY   – your LiteLLM admin key (Bearer token for management API)
    LITELLM_BASE_URL     – base URL of your LiteLLM instance, e.g. https://llm.wunderbyte.at
    TRIAL_BUDGET_USD     – optional, default 2.0  ($ credit for the trial key)
    TRIAL_DAYS           – optional, default 14   (lifetime of the trial key in days)
    TRIAL_MODELS         – optional, comma-separated; default
                           "wunderbyte-privat,wunderbyte-privat-mini,wunderbyte-embeddings"
                           (the model aliases the trial key may access; must match the
                           Moodle agent's actionconfig and exist on the proxy)

Deployment
----------
In your main FastAPI app:

    from wunderbyte_trial_endpoint import router as trial_router
    app.include_router(trial_router, prefix="/api")

The Moodle plugin will POST to  POST /api/moodle-trial
"""

import hashlib
import ipaddress
import logging
import os
import socket
from datetime import datetime, timedelta, timezone
from urllib.parse import urlparse

import httpx
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel, HttpUrl

logger = logging.getLogger(__name__)

router = APIRouter()

# ---------------------------------------------------------------------------
# Configuration (from environment)
# ---------------------------------------------------------------------------
LITELLM_BASE_URL: str = os.environ.get("LITELLM_BASE_URL", "http://localhost:4000").rstrip("/")
LITELLM_MASTER_KEY: str = os.environ.get("LITELLM_MASTER_KEY", "")
TRIAL_BUDGET_USD: float = float(os.environ.get("TRIAL_BUDGET_USD", "2.0"))
TRIAL_DAYS: int = int(os.environ.get("TRIAL_DAYS", "14"))

# LiteLLM model aliases the trial key is allowed to use. The Moodle agent maps its
# actions onto these EXACT names: wunderbyte-privat (chat / agent reply / generate_text),
# wunderbyte-privat-mini (compact planner), wunderbyte-embeddings (embeddings). All three
# must exist as models on the LiteLLM proxy. Override with a comma-separated TRIAL_MODELS
# env var only if the proxy uses different names (then align the Moodle actionconfig too).
TRIAL_MODELS: list[str] = [
    m.strip()
    for m in os.environ.get(
        "TRIAL_MODELS",
        "wunderbyte-privat,wunderbyte-privat-mini,wunderbyte-embeddings",
    ).split(",")
    if m.strip()
]

# Primary model reported back to Moodle (informational only — Moodle configures all
# three actions itself). Defaults to the first granted alias.
TRIAL_MODEL_ALIAS: str = os.environ.get(
    "TRIAL_MODEL_ALIAS", TRIAL_MODELS[0] if TRIAL_MODELS else "wunderbyte-privat"
)

# Abuse limits. Per-IP: how many trial keys one source IP may ever create. Global:
# how many trial keys may exist created within the trailing ACTIVE_WINDOW_DAYS.
# All trial keys carry the alias prefix below + request_ip/created_at in metadata.
MAX_KEYS_PER_IP: int = int(os.environ.get("TRIAL_MAX_KEYS_PER_IP", "3"))
MAX_ACTIVE_KEYS: int = int(os.environ.get("TRIAL_MAX_ACTIVE_KEYS", "500"))
ACTIVE_WINDOW_DAYS: int = int(os.environ.get("TRIAL_ACTIVE_WINDOW_DAYS", "30"))
TRIAL_ALIAS_PREFIX: str = "wunderbyte-privat-"


# ---------------------------------------------------------------------------
# Request / response schemas
# ---------------------------------------------------------------------------
class TrialRequest(BaseModel):
    wwwroot: HttpUrl        # e.g. "https://learn.example.com"
    nonce: str              # hex string generated by Moodle


class TrialResponse(BaseModel):
    apikey: str
    endpoint: str           # base URL Moodle should use (no trailing slash)
    model: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _site_id(wwwroot: str) -> str:
    """Stable, opaque identifier for a Moodle site derived from its wwwroot."""
    return hashlib.sha256(wwwroot.encode()).hexdigest()[:32]


async def _verify_origin(wwwroot: str, nonce: str) -> bool:
    """
    Back-channel challenge: fetch the Moodle challenge endpoint and check that
    it echoes back the nonce exactly.  This proves the request really originates
    from the declared domain.

    Hardened against SSRF: the wwwroot comes from the (untrusted) request body, so
    we require https and refuse any host that resolves to a private/loopback/
    link-local/reserved address, and we do NOT follow redirects (a redirect could
    bounce us onto an internal target). Residual risk: DNS rebinding between this
    resolve and httpx's own resolve — acceptable for a budget-capped trial key, but
    pin the IP here if you want belt-and-braces.
    """
    parsed = urlparse(wwwroot)
    if parsed.scheme != "https":
        logger.warning("Rejected non-https wwwroot: %s", wwwroot)
        return False
    host = parsed.hostname
    if not host or not _host_is_public(host):
        logger.warning("Rejected wwwroot with non-public/unresolvable host: %s", wwwroot)
        return False

    challenge_url = f"{wwwroot.rstrip('/')}/mod/booking/bookingextension/agent/trial_challenge.php"
    try:
        async with httpx.AsyncClient(timeout=10, follow_redirects=False) as client:
            resp = await client.get(challenge_url, params={"token": nonce})
            if resp.status_code != 200:
                logger.warning("Challenge failed for %s: HTTP %s", wwwroot, resp.status_code)
                return False
            echoed = resp.text.strip()
            if echoed != nonce:
                logger.warning(
                    "Nonce mismatch for %s: expected %r, got %r", wwwroot, nonce, echoed
                )
                return False
            return True
    except Exception as exc:
        logger.warning("Challenge request error for %s: %s", wwwroot, exc)
        return False


def _host_is_public(host: str) -> bool:
    """
    True only if every address `host` resolves to is a global/public IP. Blocks
    SSRF to loopback, RFC1918, link-local (incl. cloud metadata 169.254.169.254),
    reserved, multicast and unspecified ranges.
    """
    try:
        infos = socket.getaddrinfo(host, None)
    except OSError:
        return False
    for info in infos:
        ip = info[4][0]
        try:
            addr = ipaddress.ip_address(ip)
        except ValueError:
            return False
        if (
            addr.is_private
            or addr.is_loopback
            or addr.is_link_local
            or addr.is_reserved
            or addr.is_multicast
            or addr.is_unspecified
        ):
            return False
    return True


async def _litellm_headers() -> dict:
    return {
        "Authorization": f"Bearer {LITELLM_MASTER_KEY}",
        "Content-Type": "application/json",
    }


async def _find_existing_key(site_id: str) -> str | None:
    """
    Look for an already-issued trial key for this site in LiteLLM.
    Returns the key string if found, None otherwise.
    """
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.get(
                f"{LITELLM_BASE_URL}/key/list",
                headers=await _litellm_headers(),
                params={"key_alias": f"wunderbyte-privat-{site_id}"},
            )
            resp.raise_for_status()
            keys = resp.json().get("keys", [])
            if keys:
                return keys[0].get("key")
    except Exception as exc:
        logger.warning("Could not query existing keys: %s", exc)
    return None


def _client_ip(request: Request) -> str:
    """
    Real source IP. The service sits behind a reverse proxy, so request.client.host
    is the proxy; prefer the first hop in X-Forwarded-For. Ensure your proxy SETS a
    trustworthy XFF (and strips any client-supplied one), otherwise the per-IP cap
    can be spoofed via a forged header.
    """
    xff = request.headers.get("x-forwarded-for", "")
    if xff:
        return xff.split(",")[0].strip()
    return request.client.host if request.client else "unknown"


async def _list_trial_keys() -> list[dict] | None:
    """
    All trial keys (full objects, so metadata/created_at are available). Returns None
    if the list call fails — callers then fail OPEN (a LiteLLM hiccup must not block
    legitimate trials), which is logged loudly.
    """
    try:
        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.get(
                f"{LITELLM_BASE_URL}/key/list",
                headers=await _litellm_headers(),
                params={"return_full_object": "true", "size": 1000},
            )
            resp.raise_for_status()
            data = resp.json()
    except Exception as exc:
        logger.error("Could not list trial keys for cap enforcement: %s", exc)
        return None

    raw = data.get("keys", []) if isinstance(data, dict) else data
    out: list[dict] = []
    for k in raw:
        if not isinstance(k, dict):
            # Only key hashes were returned (no return_full_object support) -> no metadata.
            logger.warning("LiteLLM /key/list returned no full objects; per-IP cap cannot be enforced.")
            continue
        if str(k.get("key_alias") or "").startswith(TRIAL_ALIAS_PREFIX):
            out.append(k)
    return out


def _count_keys_for_ip(keys: list[dict], ip: str) -> int:
    return sum(1 for k in keys if (k.get("metadata") or {}).get("request_ip") == ip)


def _count_active_keys(keys: list[dict], window_days: int) -> int:
    cutoff = datetime.now(timezone.utc) - timedelta(days=window_days)
    n = 0
    for k in keys:
        created = (k.get("metadata") or {}).get("created_at") or k.get("created_at")
        if not created:
            n += 1  # unknown age -> count conservatively
            continue
        try:
            ts = datetime.fromisoformat(str(created).replace("Z", "+00:00"))
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            if ts >= cutoff:
                n += 1
        except ValueError:
            n += 1  # unparseable -> count conservatively
    return n


async def _create_trial_key(site_id: str, wwwroot: str, client_ip: str) -> str:
    """
    Create a new time-limited, budget-limited LiteLLM virtual key for the trial.
    The key is tagged with the site identifier so it can be found and revoked later.
    """
    expires_at = (datetime.now(timezone.utc) + timedelta(days=TRIAL_DAYS)).isoformat()

    payload = {
        "key_alias": f"wunderbyte-privat-{site_id}",
        "models": TRIAL_MODELS,
        "max_budget": TRIAL_BUDGET_USD,
        "budget_duration": f"{TRIAL_DAYS}d",
        "expires": expires_at,
        # Allow the key to read its OWN budget/usage via GET /key/info (the Moodle
        # usage bar self-looks-up with this key). Without this, keys default to
        # "llm_api_routes" only and every /key/info call is rejected with 403.
        # "llm_api_routes" must stay listed, otherwise the key can no longer chat.
        "allowed_routes": ["llm_api_routes", "/key/info"],
        "metadata": {
            "moodle_site": str(wwwroot),
            "site_id": site_id,
            "trial": True,
            # Used by the per-IP and global trailing-window caps.
            "request_ip": client_ip,
            "created_at": datetime.now(timezone.utc).isoformat(),
        },
        ## "tags": ["moodle-trial"],
    }

    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            f"{LITELLM_BASE_URL}/key/generate",
            headers=await _litellm_headers(),
            json=payload,
        )
        resp.raise_for_status()
        return resp.json()["key"]


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------
@router.post("/moodle-trial", response_model=TrialResponse)
async def request_moodle_trial(body: TrialRequest, request: Request) -> TrialResponse:
    """
    Entry point called by the Moodle bookingextension_agent plugin when an admin clicks
    "Start my free trial".

    Steps
    -----
    1. Verify the origin via back-channel challenge.
    2. Reject if this site already has a trial key.
    3. Enforce abuse caps (per-IP and global trailing window).
    4. Create a new LiteLLM virtual key scoped to the trial models.
    5. Return the key + endpoint to Moodle.
    """
    wwwroot_str = str(body.wwwroot).rstrip("/")
    site_id = _site_id(wwwroot_str)
    client_ip = _client_ip(request)

    # -- 1. Verify origin --
    origin_ok = await _verify_origin(wwwroot_str, body.nonce)
    if not origin_ok:
        raise HTTPException(
            status_code=403,
            detail=(
                "Could not verify that this request originates from "
                f"{wwwroot_str}. "
                "Make sure the Moodle site is publicly reachable."
            ),
        )

    # -- 2. Duplicate check --
    existing_key = await _find_existing_key(site_id)
    if existing_key:
        # Return a structured error that Moodle will surface as a friendly message.
        raise HTTPException(
            status_code=409,
            detail=(
                "A trial key has already been issued for this site. "
                "Please check your AI provider settings in Moodle "
                "(Site administration → AI → AI providers)."
            ),
        )

    # -- 3. Abuse caps. List failure -> fail open (logged) so a LiteLLM hiccup
    # cannot lock everyone out; the budget/expiry scoping still bounds the damage.
    trial_keys = await _list_trial_keys()
    if trial_keys is not None:
        if _count_keys_for_ip(trial_keys, client_ip) >= MAX_KEYS_PER_IP:
            logger.warning("Per-IP trial cap hit for %s", client_ip)
            raise HTTPException(
                status_code=429,
                detail="More than three keys were created for this IP.",
            )
        if _count_active_keys(trial_keys, ACTIVE_WINDOW_DAYS) >= MAX_ACTIVE_KEYS:
            logger.error("Global trial cap (%s) reached.", MAX_ACTIVE_KEYS)
            raise HTTPException(
                status_code=429,
                detail=(
                    "The trial key limit has been reached. Please try again later "
                    "or contact info@wunderbyte.at."
                ),
            )

    # -- 4. Issue a new key --
    try:
        apikey = await _create_trial_key(site_id, wwwroot_str, client_ip)
    except httpx.HTTPStatusError as exc:
        logger.error("LiteLLM key creation failed: %s", exc.response.text)
        raise HTTPException(status_code=502, detail="Failed to create trial key in LiteLLM : " + str(LITELLM_BASE_URL))

    logger.info("Issued trial key for site %s (id=%s)", wwwroot_str, site_id)

    return TrialResponse(
        apikey=apikey,
        endpoint=LITELLM_BASE_URL,
        model=TRIAL_MODEL_ALIAS,
    )
